version: '3.7'

services:
  web:
    build: "./linux"
    container_name: "web_baseball"
    platform: linux/x86_64
    ports:
      - 80:80
      - 443:443
      - 22:22
    # コンテナに配置するファイルの場所、webアプリケーションの構成に合わせて変更
    volumes:
      - ../src:/var/www/
    privileged: true
    tty: true
    stdin_open: true
    depends_on:
      - mysql
    networks:
      - br0
  mysql:
    #mysqlのバージョンに合わせて変更
    image: mysql:8.0.29
    container_name: "db_baseball"
    platform: linux/x86_64
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 't_baseball'
      MYSQL_USER: tooiea
      MYSQL_PASSWORD: touya1008
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
    networks:
      - br0
  phpmyadmin:
    container_name: "oldws_phpmyadmin"
    platform: linux/x86_64
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - 8080:80
    volumes: 
            - ./phpmyadmin/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
  mailhog:
    image: mailhog/mailhog
    container_name: oldws_mailhog
    restart: always
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - br0
volumes:
    db_data: {}

networks:
  br0:
    driver: bridge