version: '3'

services:
  db_baseball:
    build: ./db_baseball
    image: db_baseball
    container_name: db_baseball
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 't_baseball'
      MYSQL_USER: tooiea
      MYSQL_PASSWORD: touya1008
    networks:
      - br0

  web_baseball:
    build: ./web_baseball
    image: web_baseball
    container_name: web_baseball
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ../src:/var/www/src
    depends_on:
      - db_baseball
    tty: true
    stdin_open: true
    networks:
      - br0

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - br0

  phpmyadmin:
    container_name: "oldws_phpmyadmin"
    platform: linux/x86_64
    depends_on:
      - db_baseball
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db_baseball
    ports:
      - 8080:80
    volumes:
      - ./phpmyadmin/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
    networks:
      - br0

volumes:
  db_baseball:


networks:
  br0:
    driver: bridge
