name: Sync to Backlog
on:
  push:
    branches:
      - master
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.BACKLOG_SSH_PRIVATE_KEY }}

    # - name: Add Backlog remote
    #   run: |
    #     git remote add backlog https://tooiea.backlog.com/git/OLDWS/system_php.git

    - name: Push to Backlog
      run: |
        git remote add mirror ssh://git@tooiea.git.backlog.jp:22/https://tooiea.backlog.com/git/OLDWS/system_php.git
        git push --mirror mirror