name: Sync to Backlog
on:
  push:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: webfactory/ssh-agent@v0.9.0
          with:
              ssh-private-key: ${{ secrets.BACKLOG_SSH_PRIVATE_KEY }}
              
        - name: Push to Backlog
          run: |
            git remote add mirror ssh://git@tooiea.git.backlog.jp:22/OLDWS/system_php.git
            git push mirror --all
            git push mirror --tags