name: Sync to Backlog
on:
  push:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.BACKLOG_SSH_PRIVATE_KEY }}
      
      - name: Add SSH Host Key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H tooiea.git.backlog.com >> ~/.ssh/known_hosts
      
      - name: Push to Backlog
        run: |
          git remote add mirror ssh://git@tooiea.git.backlog.com:22/OLDWS/system_php.git
          git push mirror --all
          git push mirror --tags
      
      - name: Stop SSH Agent
        if: always()
        run: |
          pkill ssh-agent || true