name: Sync to Backlog
on:
  push:
    branches:
      - master
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # TODO 要件に合わせて調整する

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.BACKLOG_SSH_PRIVATE_KEY }}

    - name: Add Backlog remote
      run: |
        git remote add backlog https://tooiea.backlog.com/git/OLDWS/system_php.git

    - name: Push to Backlog
      run: |
        ssh-keyscan -H tooiea.backlog.com >> ~/.ssh/known_hosts
        git push backlog