name: Sync to Backlog
on:
  push:
    branches:
      - master
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        # Make sure the @v0.9.0 matches the current version of the action
        - uses: webfactory/ssh-agent@v0.9.0
          with:
              ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

        # - name: Setup SSH
        #   run: |
        #     ssh-keyscan -H tooiea.git.backlog.jp >> ~/.ssh/known_hosts

        - name: Push to Backlog
          run: |
            git remote add mirror ssh://git@tooiea.git.backlog.jp:22/OLDWS/system_php.git
            git push mirror --all
            git push mirror --tags